/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;
import Controller.ControllerSell;
import javax.swing.JOptionPane;
/**
 *
 * @author Andrey Orozco
 */
public class SellView extends javax.swing.JPanel {
    ControllerSell controlador;
    
    /**
     * Creates new form Sell
     */
    public SellView() {
        controlador=new ControllerSell();
        initComponents();
        llenarComboBox();
    }
    public void llenarComboBox(){
        for(int i=0;i<3;i++){
            this.TipoCom.addItem(controlador.getCombustible(i).getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Venta = new javax.swing.JPanel();
        TipoCombustible = new javax.swing.JLabel();
        PrecioGalon = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        PrecioVenta = new javax.swing.JLabel();
        TipoCom = new javax.swing.JComboBox<>();
        PrecioG = new javax.swing.JLabel();
        Galones = new javax.swing.JTextField();
        PrecioV = new javax.swing.JLabel();
        Registro = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(490, 300));
        setMinimumSize(new java.awt.Dimension(490, 300));
        setPreferredSize(new java.awt.Dimension(490, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Venta.setBackground(new java.awt.Color(51, 51, 51));
        Venta.setMaximumSize(new java.awt.Dimension(490, 300));
        Venta.setMinimumSize(new java.awt.Dimension(490, 300));
        Venta.setPreferredSize(new java.awt.Dimension(490, 300));

        TipoCombustible.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        TipoCombustible.setForeground(new java.awt.Color(204, 255, 255));
        TipoCombustible.setText("TIPO DE COMBUSTIBLE: ");

        PrecioGalon.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        PrecioGalon.setForeground(new java.awt.Color(204, 255, 255));
        PrecioGalon.setText("PRECIO GALÓN:");

        Cantidad.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        Cantidad.setForeground(new java.awt.Color(204, 255, 255));
        Cantidad.setText("CANTIDAD:");

        PrecioVenta.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        PrecioVenta.setForeground(new java.awt.Color(204, 255, 255));
        PrecioVenta.setText("PRECIO:");

        TipoCom.setBackground(new java.awt.Color(51, 51, 51));
        TipoCom.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        TipoCom.setForeground(new java.awt.Color(204, 255, 255));
        TipoCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoComActionPerformed(evt);
            }
        });

        PrecioG.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        PrecioG.setForeground(new java.awt.Color(204, 255, 255));
        PrecioG.setText("jLabel6");

        Galones.setBackground(new java.awt.Color(102, 102, 102));
        Galones.setForeground(new java.awt.Color(255, 255, 255));
        Galones.setText("0");
        Galones.setBorder(null);
        Galones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GalonesActionPerformed(evt);
            }
        });

        PrecioV.setForeground(new java.awt.Color(204, 255, 255));
        PrecioV.setText("jLabel7");

        Registro.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        Registro.setText("REGISTRAR");
        Registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VENTAS");

        javax.swing.GroupLayout VentaLayout = new javax.swing.GroupLayout(Venta);
        Venta.setLayout(VentaLayout);
        VentaLayout.setHorizontalGroup(
            VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentaLayout.createSequentialGroup()
                .addGroup(VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentaLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoCombustible)
                            .addComponent(PrecioGalon)
                            .addComponent(Cantidad)
                            .addComponent(PrecioVenta))
                        .addGap(66, 66, 66)
                        .addGroup(VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PrecioV)
                            .addComponent(PrecioG)
                            .addComponent(TipoCom, 0, 125, Short.MAX_VALUE)
                            .addComponent(Galones)
                            .addComponent(jSeparator1)))
                    .addGroup(VentaLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(Registro))
                    .addGroup(VentaLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        VentaLayout.setVerticalGroup(
            VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoCombustible)
                    .addComponent(TipoCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioGalon)
                    .addComponent(PrecioG))
                .addGap(22, 22, 22)
                .addGroup(VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cantidad)
                    .addComponent(Galones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioVenta)
                    .addComponent(PrecioV))
                .addGap(50, 50, 50)
                .addComponent(Registro)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        add(Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TipoComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoComActionPerformed
        int i=TipoCom.getSelectedIndex();
        PrecioG.setText(String.valueOf(controlador.getCombustible(i).getPrecioG()));
        float temp=Float.parseFloat(Galones.getText());
        PrecioV.setText(String.valueOf((controlador.getCombustible(i).getPrecioG())*temp));
    }//GEN-LAST:event_TipoComActionPerformed

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
        String nombre=controlador.getCombustible(TipoCom.getSelectedIndex()).getNombre();
        float cantidad=Float.parseFloat(Galones.getText());
        float total=(controlador.getCombustible(TipoCom.getSelectedIndex()).getPrecioG()*cantidad);
        if(cantidad>0.1){
        controlador.Insertar(nombre,cantidad,total);
        System.out.println("Insertado con exito");
        }else{
        JOptionPane.showMessageDialog(null, "La cantidad de galones debe ser mayor a 0.1 ");
        }
    }//GEN-LAST:event_RegistroActionPerformed

    private void GalonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GalonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GalonesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JTextField Galones;
    private javax.swing.JLabel PrecioG;
    private javax.swing.JLabel PrecioGalon;
    private javax.swing.JLabel PrecioV;
    private javax.swing.JLabel PrecioVenta;
    private javax.swing.JButton Registro;
    private javax.swing.JComboBox<String> TipoCom;
    private javax.swing.JLabel TipoCombustible;
    private javax.swing.JPanel Venta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
