/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;
import Controller.ControllerTable;
import Model.Venta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Andrey Orozco
 */
public class TableSells extends javax.swing.JPanel {
    ControllerTable controlador;
    /**
     * Creates new form Table
     */
    public TableSells() {
        initComponents();
        controlador=new ControllerTable();
        llenarTable();
    }
    public void llenarTable(){
        ArrayList<Venta> lista = new ArrayList<>();
        lista=controlador.llenar();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Combustible","Cantidad", "Precio", "Fecha"});
        Ventas.setModel(model);
        for(Venta v:lista){
            model.addRow(new Object[]{v.getNombre(),v.getCantidad(),v.getPrecioTotal(),v.getFecha()});
        }
        Ventas.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reporte = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ventas = new javax.swing.JTable();
        TipoReporte = new javax.swing.JLabel();
        Tipo = new javax.swing.JComboBox<>();
        Generar = new javax.swing.JButton();

        Reporte.setBackground(new java.awt.Color(51, 51, 51));
        Reporte.setMaximumSize(new java.awt.Dimension(490, 300));
        Reporte.setMinimumSize(new java.awt.Dimension(490, 300));
        Reporte.setPreferredSize(new java.awt.Dimension(490, 300));
        Reporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(500, 300));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(500, 300));

        Ventas.setBackground(new java.awt.Color(102, 102, 102));
        Ventas.setForeground(new java.awt.Color(51, 51, 51));
        Ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Combustible", "Cantidad", "Precio", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Ventas);
        if (Ventas.getColumnModel().getColumnCount() > 0) {
            Ventas.getColumnModel().getColumn(0).setResizable(false);
            Ventas.getColumnModel().getColumn(1).setResizable(false);
            Ventas.getColumnModel().getColumn(2).setResizable(false);
            Ventas.getColumnModel().getColumn(3).setResizable(false);
        }

        Reporte.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 478, 219));

        TipoReporte.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        TipoReporte.setForeground(new java.awt.Color(204, 255, 255));
        TipoReporte.setText("Generar reporte :");
        Reporte.add(TipoReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 255, -1, -1));

        Tipo.setBackground(new java.awt.Color(51, 51, 51));
        Tipo.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        Tipo.setForeground(new java.awt.Color(204, 255, 255));
        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Gasolina", "Diesel", "GNV" }));
        Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActionPerformed(evt);
            }
        });
        Reporte.add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 252, 88, -1));

        Generar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Generar.setText("GENERAR");
        Generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarActionPerformed(evt);
            }
        });
        Reporte.add(Generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 252, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarActionPerformed
        controlador.generarReporte((String)Tipo.getSelectedItem());
                JOptionPane.showMessageDialog(null, 
                "Se creo el reporte "+ Tipo.getSelectedItem().toString()+" ");
    }//GEN-LAST:event_GenerarActionPerformed

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Generar;
    private javax.swing.JPanel Reporte;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JLabel TipoReporte;
    private javax.swing.JTable Ventas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
